name: 'Instagram Feed Action'
author: 'Alex Queudot'
description: 'Allows you to show your latest instagram posts on your github profile or project readme'

inputs:
  account:
    description: "The name of the instagram account to use"
    default: ""
    required: true
  max_post_count:
    description: 'Maximum number of posts you want to show on your readme'
    default: '6'
    required: false
  image_size:
    description: 'Image dimension in pixels for each post'
    default: '250'
    required: false
  image_margin:
    description: 'Margin between post images'
    default: '10'
    required: false
  images_directory:
    description: 'Directory where images are stored'
    default: './images/instagram'
    required: false
  gh_token:
    description: 'GitHub access token with Repo scope'
    required: false
    default: ${{ github.token }}
  readme_path:
    description: 'Path of the readme file you want to update'
    default: './README.md'
    required: false
  commit_message:
    description: "Commit message used while committing to the repo"
    default: "Updated with the latest instagram posts"
    required: false
  committer_username:
    description: "Username used while committing to the repo"
    default: "instagram-feed-bot"
    required: false
  committer_email:
    description: "Email id used while committing to the repo"
    default: "instagram-feed-bot@example.com"
    required: false

runs:
  using: node12
  main: dist/index.js
branding:
  icon: 'activity'
  color: 'purple'